'use strict';
const IST='Asia/Kolkata';
const DEFAULT_HOLIDAYS_2026=['2026-01-26','2026-03-03','2026-03-26','2026-03-31','2026-04-03','2026-04-14','2026-05-01','2026-05-28','2026-06-26','2026-09-14','2026-10-02','2026-10-20','2026-11-10','2026-11-24','2026-12-25'];
function istParts(value=new Date()){const d=value instanceof Date?value:new Date(value);const p=Object.fromEntries(new Intl.DateTimeFormat('en-GB',{timeZone:IST,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false,weekday:'short'}).formatToParts(d).filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));return{date:p.year+'-'+p.month+'-'+p.day,weekday:p.weekday,minutes:Number(p.hour)*60+Number(p.minute),time:p.hour+':'+p.minute+':'+p.second};}
function isTradingDay(date,holidays=new Set(DEFAULT_HOLIDAYS_2026)){const p=istParts(new Date(date+'T12:00:00+05:30'));return !['Sat','Sun'].includes(p.weekday)&&!holidays.has(date);}
function recordDate(row){try{return istParts(row.timestamp).date;}catch(_){return null;}}
function latestIso(rows,predicate=()=>true){let latest=null;for(const r of rows||[]){if(!predicate(r)||!r.timestamp)continue;const t=new Date(r.timestamp).getTime();if(Number.isFinite(t)&&(!latest||t>latest.t))latest={t,iso:r.timestamp};}return latest?.iso||null;}
function opportunityKey(r){const legs=Object.entries(r?.tradeLegs||{}).filter(([,x])=>x&&typeof x==='object'&&x.contractId).map(([n,x])=>n+':'+x.contractId).sort().join(',');return String(r?.strategy||'WAIT')+'|'+legs;}
function daySummary(rows,date){const day=(rows||[]).filter(r=>recordDate(r)===date);const polls=day.filter(r=>r.recordType==='POLL_SNAPSHOT').sort((a,b)=>new Date(a.timestamp)-new Date(b.timestamp));const outcomes=day.filter(r=>r.recordType==='OUTCOME');let readyEpisodes=0,prevReady=false,prevKey=null;for(const r of polls){const ready=r.orchestrationStatus==='READY_TO_EXECUTE',key=ready?opportunityKey(r):null;if(ready&&(!prevReady||key!==prevKey))readyEpisodes++;prevReady=ready;prevKey=key;}return{date,polls:polls.length,readyEpisodes,outcomes:outcomes.length,measuredOutcomes:outcomes.filter(r=>r.outcome?.status==='MEASURED').length,noTradeDay:polls.length>0&&readyEpisodes===0,lastAppend:latestIso(day)};}
function distinctDates(rows){return[...new Set((rows||[]).map(recordDate).filter(Boolean))].sort();}
function buildEvidenceHealth({rows=[],storage={},archive={},harvester={},now=new Date(),holidays=new Set(DEFAULT_HOLIDAYS_2026),staleAfterMinutes=5}={}){const p=istParts(now),today=daySummary(rows,p.date),tradingDay=isTradingDay(p.date,holidays),marketOpen=tradingDay&&p.minutes>=555&&p.minutes<930,lastAppend=latestIso(rows),appendAgeMinutes=lastAppend?Math.max(0,(now.getTime()-new Date(lastAppend).getTime())/60000):null,appendFresh=!marketOpen||(appendAgeMinutes!==null&&appendAgeMinutes<=staleAfterMinutes),archiveSynced=!!archive.lastBackup&&!!lastAppend&&new Date(archive.lastBackup)>=new Date(lastAppend)&&!archive.lastError,days=distinctDates(rows).filter(d=>isTradingDay(d,holidays)).map(d=>daySummary(rows,d));const issues=[];if(storage.writeError)issues.push('STORAGE_WRITE_ERROR');if(marketOpen&&!appendFresh)issues.push('APPEND_STALE_DURING_MARKET');if(archive.configured&&archive.lastError)issues.push('ARCHIVE_ERROR');if(archive.configured&&!archiveSynced)issues.push('ARCHIVE_NOT_CAUGHT_UP');if(harvester.lastError)issues.push('HARVESTER_ERROR');return{version:'EVIDENCE_HEALTH_V1',timestamp:now.toISOString(),session:{date:p.date,tradingDay,marketOpen,calendar:'NSE_FO_2026',staleAfterMinutes},healthy:issues.length===0,issues,lastAppend,appendAgeMinutes:appendAgeMinutes===null?null:Number(appendAgeMinutes.toFixed(1)),appendFresh,today,verifiedMarketDays:days.filter(d=>!(d.date===p.date&&marketOpen)&&d.polls>0).length,retainedTradingDays:days.length,noTradeDays:days.filter(d=>d.noTradeDay).length,storage:{durable:!!storage.durable,writeError:storage.writeError||null},archive:{configured:!!archive.configured,lastBackup:archive.lastBackup||null,lastRestore:archive.lastRestore||null,lastVerification:archive.lastVerification||null,recordsBackedUp:archive.recordsBackedUp||0,syncedThroughLastAppend:archiveSynced,lastError:archive.lastError||null},harvester:{lastRun:harvester.lastRun||null,lastError:harvester.lastError||null,measured:harvester.measured||0,pending:harvester.pending||0,running:!!harvester.running}};}
module.exports={DEFAULT_HOLIDAYS_2026,istParts,isTradingDay,daySummary,buildEvidenceHealth};
